// app/layout.tsx
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/lib/NavBar";
import { ReactNode } from "react";
import { usePathname } from 'next/navigation';
const montserrat = Montserrat({ 
  subsets: ["latin"],
  variable: '--font-montserrat',
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-sans`}>
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}

// 👇 Helper component using client hooks
'use client';


const LayoutWrapper = ({ children }: { children: ReactNode }) => {
  const pathname = usePathname();

  // List of routes where the navbar should be hidden
  const hiddenNavRoutes = ['/login', '/signup', '/forgot-password'];

  const showNavbar = !hiddenNavRoutes.includes(pathname);

  return (
    <>
      {showNavbar && <NavBar />}
      <main className={showNavbar ? "mt-[100px]" : ""}>
        {children}
      </main>
    </>
  );
};
